(function(global) {
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        handleGAEBFileUpload: global.handleGAEBFileUpload,
        renderGAEBPositionsTable: global.renderGAEBPositionsTable,
        switchAufmassSubTab: global.switchAufmassSubTab,
        loadSplitViewPositions: global.loadSplitViewPositions,
        renderSplitPositionsTable: global.renderSplitPositionsTable,
        selectSplitPosition: global.selectSplitPosition,
        addSplitAufmassZeile: global.addSplitAufmassZeile,
        removeSplitAufmassZeile: global.removeSplitAufmassZeile,
        toggleSplitZeileVorzeichen: global.toggleSplitZeileVorzeichen,
        renderSplitDetailZeilenTable: global.renderSplitDetailZeilenTable,
        calcSplitZeileFormula: global.calcSplitZeileFormula,
        recalcSplitDetailTotal: global.recalcSplitDetailTotal,
        saveSplitDetailAufmass: global.saveSplitDetailAufmass,
        selectAufmassWizardTyp: global.selectAufmassWizardTyp,
        selectAufmassWizardVariante: global.selectAufmassWizardVariante,
        openAufmassWizardModal: global.openAufmassWizardModal,
        closeAufmassWizardModal: global.closeAufmassWizardModal,
        wizardNextStep: global.wizardNextStep,
        wizardPrevStep: global.wizardPrevStep,
        updateWizardBadges: global.updateWizardBadges,
        finishAufmassWizard: global.finishAufmassWizard,
        openFormelassistentModal: global.openFormelassistentModal,
        closeFormelassistentModal: global.closeFormelassistentModal,
        onFormelVorlageChange: global.onFormelVorlageChange,
        onCustomFormulaInput: global.onCustomFormulaInput,
        parseAndBuildParameterInputs: global.parseAndBuildParameterInputs,
        recalcFormelassistentLive: global.recalcFormelassistentLive,
        applyFormelassistentResult: global.applyFormelassistentResult,
        loadProjektAufmassBlaetter: global.loadProjektAufmassBlaetter,
        openAufmassBlattModal: global.openAufmassBlattModal,
        closeAufmassBlattModal: global.closeAufmassBlattModal,
        addAufmassBlattZeile: global.addAufmassBlattZeile,
        removeAufmassBlattZeile: global.removeAufmassBlattZeile,
        toggleAufmassZeileVorzeichen: global.toggleAufmassZeileVorzeichen,
        renderAufmassBlattZeilenTable: global.renderAufmassBlattZeilenTable,
        updateAufmassZeile: global.updateAufmassZeile,
        calcAufmassZeileFormula: global.calcAufmassZeileFormula,
        saveAufmassBlattData: global.saveAufmassBlattData,
        deleteAufmassBlattAction: global.deleteAufmassBlattAction,
        exportProjektDA11: global.exportProjektDA11,
        exportProjektGAEBX31: global.exportProjektGAEBX31,
        importProjektGAEBX31: global.importProjektGAEBX31
    };
}
})(typeof window !== 'undefined' ? window : this);
